apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: alfa3-bd-postgres
  labels:
    app: alfa3-bd-postgres
spec:
  serviceName: alfa3-bd-postgres
  replicas: 1
  selector:
    matchLabels:
      app: alfa3-bd-postgres
  template:
    metadata:
      labels:
        app: alfa3-bd-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          value: root
        - name: POSTGRES_PASSWORD
          value: root
        - name: POSTGRES_DB
          value: core
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/alfa3
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d
          readOnly: true
      volumes:
      - name: init-scripts
        configMap:
          name: postgres-init-scripts
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: alfa3-bd-postgres
  labels:
    app: alfa3-bd-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: alfa3-bd-postgres